controller_list:
  - name: fake_right_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_left_arm_controller
    joints:
      - joint_12
      - joint_22
      - joint_32
      - joint_42
      - joint_52
      - joint_62
  - name: fake_arms_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_12
      - joint_22
      - joint_32
      - joint_42
      - joint_52
      - joint_62